install:
  - choco install gitversion.portable -pre -y
  - choco install ikvm
  - ps: |
      (new-object net.webclient).DownloadFile('https://github.com/concordion/concordion.net/files/695457/Concordion_1.5.1-IKVM-Base.zip', 'Concordion.zip')
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      Expand-Archive Concordion.zip -DestinationPath Concordion
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

before_build:
  - nuget.exe restore Concordion.sln -verbosity detailed
  - ps: gitversion /l console /output buildserver

build:
  project: Concordion.sln
  
after_build:
  - cmd: Concordion\build.cmd

configuration:
  - Release

notifications:
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
