install:
  - choco install gitversion.portable -pre -y
  - choco install ikvm

before_build:
  - nuget.exe restore Concordion.sln -verbosity detailed
  - ps: gitversion /l console /output buildserver

build:
  project: Concordion.sln
  
after_build:
  - cmd: Concordion\build.cmd

configuration:
  - Release

notifications:
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
